platosPrincipales = {
        (0, 0, 0, 0, 0, 0, 0): ("Tofu salteado",["Arroz integral","Verduras al vapor","Puré de manzana"]),
        (0, 0, 0, 0, 0, 0, 1): ("Pollo a la plancha",["Ensalada mixta","Arroz integral","Verduras al vapor","Puré de manzana","Risotto de hongos"]),
        (0, 0, 0, 0, 0, 1, 0): ("Pescado al horno",["Puré de papas"]),
        (0, 0, 0, 0, 0, 1, 1): ("Pavo a la parrilla",["Batatas fritas cubiertas con crema agria","Batatas asadas"]),
        (0, 0, 0, 0, 1, 0, 0): ("Conejo al horno",["Puré de papas","Batatas asadas"]),
        (0, 0, 0, 0, 1, 0, 1): ("Filete de ternera a la plancha",["Batatas fritas cubiertas con crema agria","Batatas asadas","Papas fritas con cheddar y panceta"]),
        (0, 0, 0, 0, 1, 1, 0): ("Conejo a la parrilla",["Puré de papas","Batatas asadas"]),
        (0, 0, 0, 0, 1, 1, 1): ("Conejo al vapor",["Sopa"]),
        (0, 0, 0, 1, 0, 0, 0): ("Pechuga de pavo al horno",["Ensalada mixta","Arroz integral","Verduras al vapor","Puré de manzana","Risotto de hongos"]),
        (0, 0, 0, 1, 0, 0, 1): ("Lubina a la parrilla",["Champiñones salteados","Espárragos a la parrilla"]),
        (0, 0, 0, 1, 0, 1, 0): ("Pargo al vapor",[]),
        (0, 0, 0, 1, 0, 1, 1): ("Pollo al curry",["Sopa","Puré de manzana"]),
        (0, 0, 0, 1, 1, 0, 0): ("Ternera salteada",["Champiñones salteados","Verduras al vapor"]),
        (0, 0, 0, 1, 1, 0, 1): ("Pechuga de pato a la plancha",["Ensalada mixta","Arroz integral","Verduras al vapor","Puré de manzana","Risotto de hongos"]),
        (0, 0, 0, 1, 1, 1, 0): ("Pollo a la brasa",["Batatas asadas"]),
        (0, 0, 0, 1, 1, 1, 1): ("Pavo al curry",["Sopa","Lentejas","Porotos"]),
        (0, 0, 1, 0, 0, 0, 0): ("Tofu a la parrilla",["Sopa","Lentejas","Porotos"]),
        (0, 0, 1, 0, 0, 0, 1): ("Pescado al grill",["Champiñones salteados","Puré de papas"]),
        (0, 0, 1, 0, 0, 1, 0): ("Pollo al limón",["Ensalada mixta","Arroz integral","Verduras al vapor","Puré de manzana","Risotto de hongos"]),
        (0, 0, 1, 0, 0, 1, 1): ("Lomo de cerdo a la brasa",["Puré de manzána","Batatas fritas cubiertas con crema agria"]),
        (0, 0, 1, 0, 1, 0, 0): ("Filete de ternera al horno",["Arroz integral","Puré de papas"]),
        (0, 0, 1, 0, 1, 0, 1): ("Lomo de cerdo al horno", ["Ensalada mixta", "Puré de papas"]),
        (0, 0, 1, 0, 1, 1, 0): ("Cordero a la parrilla", ["Arroz blanco", "Espárragos a la parrilla"]),
        (0, 0, 1, 0, 1, 1, 1): ("Lomo de cerdo a la plancha", ["Ensalada mixta", "Arroz blanco"]),
        (0, 0, 1, 1, 0, 0, 0): ("Carne magra a la parrilla", ["Ensalada mixta", "Verduras al vapor"]),
        (0, 0, 1, 1, 0, 0, 1): ("Filete de ternera al grill", ["Verduras al vapor", "Puré de manzana"]),
        (0, 0, 1, 1, 0, 1, 0): ("Pollo al ajillo", ["Arroz integral", "Porotos"]),
        (0, 0, 1, 1, 0, 1, 1): ("Pargo al grill", ["Ensalada mixta", "Espárragos a la parrilla"]),
        (0, 0, 1, 1, 1, 0, 0): ("Ternera al curry", ["Arroz integral", "Lentejas"]),
        (0, 0, 1, 1, 1, 0, 1): ("Pollo al horno", ["Ensalada mixta", "Puré de manzana"]),
        (0, 0, 1, 1, 1, 1, 0): ("Salmón a la parrilla", ["Ensalada mixta", "Verduras al vapor"]),
        (0, 0, 1, 1, 1, 1, 1): ("Salmón al vapor", ["Ensalada mixta", "Verduras al vapor"]),
        (0, 1, 0, 0, 0, 0, 0): ("Tacos de pescado con salsa de yogur", ["Ensalada mixta", "Arroz blanco"]),
        (0, 1, 0, 0, 0, 0, 1): ("Ensalada de atún con aguacate y tomate", ["Ensalada mixta"]),
        (0, 1, 0, 0, 0, 1, 0): ("Tofu a la parrilla con salsa de maní", ["Ensalada mixta", "Arroz integral"]),
        (0, 1, 0, 0, 0, 1, 1): ("Tofu al curry con leche de coco y espinacas", ["Arroz integral", "Verduras al vapor"]),
        (0, 1, 0, 0, 1, 0, 0): ("Tofu salteado con vegetales y salsa de soja", ["Ensalada mixta", "Verduras al vapor"]),
        (0, 1, 0, 0, 1, 0, 1): ("Estofado de verduras con tofu", ["Verduras al vapor", "Arroz integral"]),
        (0, 1, 0, 0, 1, 1, 0): ("Wrap de pollo a la parrilla y vegetales", ["Ensalada mixta", "Arroz blanco"]),
        (0, 1, 0, 0, 1, 1, 1): ("Pechuga de pollo al limón", ["Ensalada mixta", "Puré de papas"]),
        (0, 1, 0, 1, 0, 0, 0): ("Lomo de cerdo a la mostaza y miel", ["Arroz blanco", "Puré de manzana"]),
        (0, 1, 0, 1, 0, 0, 1): ("Salmón a la parrilla con salsa de eneldo", ["Ensalada mixta", "Espárragos a la parrilla"]),
        (0, 1, 0, 1, 0, 1, 0): ("Pechuga de pavo rellena de espinacas y queso feta", ["Ensalada mixta", "Batatas asadas"]),
        (0, 1, 0, 1, 0, 1, 1): ("Ensalada de quinoa con verduras asadas", ["Ensalada mixta", "Champiñones salteados"]),
        (0, 1, 0, 1, 1, 0, 0): ("Pollo teriyaki con brócoli y zanahorias", ["Ensalada mixta", "Arroz integral"]),
        (0, 1, 0, 1, 1, 0, 1): ("Pargo al horno con costra de hierbas", ["Ensalada mixta", "Espárragos a la parrilla"]),
        (0, 1, 0, 1, 1, 1, 0): ("Filete de ternera con champiñones y salsa de vino tinto", ["Ensalada mixta", "Papas fritas con cheddar y panceta"]),
        (0, 1, 0, 1, 1, 1, 1): ("Pechuga de pollo a la mostaza y hierbas", ["Ensalada mixta", "Arroz integral"]),
        (0, 1, 1, 0, 0, 0, 0): ("Pasta integral con verduras salteadas", ["Ensalada mixta", "Champiñones salteados"]),
        (0, 1, 1, 0, 0, 0, 1): ("Rollitos de lechuga con pollo a la parrilla", ["Ensalada mixta", "Verduras al vapor"]),
        (0, 1, 1, 0, 0, 1, 0): ("Salmón al vapor con espárragos y limón", ["Ensalada mixta", "Arroz integral"]),
        (0, 1, 1, 0, 0, 1, 1): ("Tacos de pollo con salsa de yogur y cilantro", ["Ensalada mixta", "Arroz blanco"]),
        (0, 1, 1, 0, 1, 0, 0): ("Lomo de cerdo a la parrilla con salsa de piña", ["Ensalada mixta", "Batatas asadas"]),
        (0, 1, 1, 0, 1, 0, 1): ("Ensalada de garbanzos con tomate y pepino", ["Ensalada mixta", "Puré de papas"]),
        (0, 1, 1, 0, 1, 1, 0): ("Pechuga de pavo a la plancha con salsa de arándanos", ["Ensalada mixta", "Arroz integral"]),
        (0, 1, 1, 0, 1, 1, 1): ("Pescado al curry con leche de coco", ["Ensalada mixta", "Arroz blanco"]),
        (0, 1, 1, 1, 0, 0, 0): ("Wrap de salmón ahumado con queso crema bajo en grasa", ["Ensalada mixta", "Verduras al vapor"]),
        (0, 1, 1, 1, 0, 0, 1): ("Pollo al horno con especias y limón", ["Arroz blanco", "Verduras al vapor"]),
        (0, 1, 1, 1, 0, 1, 0): ("Berenjenas rellenas de quinoa y vegetales", ["Ensalada mixta", "Puré de manzana"]),
        (0, 1, 1, 1, 0, 1, 1): ("Lomo de cerdo con salsa de ciruela", ["Puré de papas", "Verduras al vapor"]),
        (0, 1, 1, 1, 1, 0, 0): ("Pavo al horno con hierbas y limón", ["Ensalada mixta", "Arroz integral"]),
        (0, 1, 1, 1, 1, 0, 1): ("Salmón al grill con salsa de aguacate", ["Espárragos a la parrilla", "Puré de papas"]),
        (0, 1, 1, 1, 1, 1, 0): ("Ensalada de pollo a la parrilla con aguacate y nueces", ["Ensalada mixta", "Lentejas"]),
        (0, 1, 1, 1, 1, 1, 1): ("Ensalada de salmón y aguacate", ["Ensalada mixta", "Verduras al vapor"]),
        (1, 0, 0, 0, 0, 0, 0): ("Pollo al curry con leche de coco", ["Arroz blanco", "Porotos"]),
        (1, 0, 0, 0, 0, 0, 1): ("Ensalada César con pollo a la parrilla", ["Ensalada mixta", "Champiñones salteados"]),
        (1, 0, 0, 0, 0, 1, 0): ("Pasta Alfredo con camarones", ["Ensalada mixta", "Sopa"]),
        (1, 0, 0, 0, 0, 1, 1): ("Lomo de cerdo con salsa de champiñones", ["Papas fritas con cheddar y panceta", "Verduras al vapor"]),
        (1, 0, 0, 0, 1, 0, 0): ("Risotto de hongos y queso parmesano", ["Espárragos a la parrilla", "Champiñones salteados"]),
        (1, 0, 0, 0, 1, 0, 1): ("Pechuga de pollo rellena de espinacas y queso ricotta", ["Puré de papas", "Verduras al vapor"]),
        (1, 0, 0, 0, 1, 1, 0): ("Salmón glaseado con miel y mostaza", ["Arroz integral", "Espárragos a la parrilla"]),
        (1, 0, 0, 0, 1, 1, 1): ("Pescado a la mantequilla con almendras" ,["Arroz blanco", "Espárragos a la parrilla"]),
        (1, 0, 0, 1, 0, 0, 0): ("Lasaña de carne con queso mozzarella" ,["Ensalada mixta", "Papas fritas con cheddar y panceta"]),
        (1, 0, 0, 1, 0, 0, 1): ("Pechuga de pollo a la parmesana con salsa marinara" ,["Ensalada mixta", "Macarrones con queso"]),
        (1, 0, 0, 1, 0, 1, 0): ("Pollo al horno con papas asadas y verduras", ["Ensalada mixta", "Verduras al vapor"]),
        (1, 0, 0, 1, 0, 1, 1): ("Tacos de carne asada con guacamole", ["Arroz blanco", "Puré de manzana"]),
        (1, 0, 0, 1, 1, 0, 0): ("Tacos de cerdo desmenuzado con salsa de chipotle", ["Arroz integral", "Sopa"]),
        (1, 0, 0, 1, 1, 0, 1): ("Filete de ternera con salsa de vino tinto y champiñones", ["Espárragos a la parrilla", "Champiñones salteados"]),
        (1, 0, 0, 1, 1, 1, 0): ("Pasta con salsa de crema de cuatro quesos", ["Ensalada mixta", "Macarrones con queso"]),
        (1, 0, 0, 1, 1, 1, 1): ("Chuletas de cordero con hierbas provenzales", ["Verduras al vapor", "Batatas asadas"]),
        (1, 0, 1, 0, 0, 0, 0): ("Pollo teriyaki con arroz frito", ["Porotos", "Arroz integral"]),
        (1, 0, 1, 0, 0, 0, 1): ("Raviolis de queso con salsa de tomate y albahaca", ["Champiñones salteados", "Sopa"]),
        (1, 0, 1, 0, 0, 1, 0): ("Pescado al horno con costra de hierbas y limón", ["Ensalada mixta", "Puré de papas"]),
        (1, 0, 1, 0, 0, 1, 1): ("Pollo a la parrilla con salsa de champiñones y vino blanco", ["Arroz blanco", "Espárragos a la parrilla"]),
        (1, 0, 1, 0, 1, 0, 0): ("Ternera salteada con verduras y salsa de soja", ["Lentejas", "Batatas asadas"]),
        (1, 0, 1, 0, 1, 0, 1): ("Pasta con salsa de tomate y albóndigas", ["Ensalada mixta", "Macarrones con queso"]),
        (1, 0, 1, 0, 1, 1, 0): ("Pollo a la parrilla con pesto de albahaca", ["Verduras al vapor", "Puré de papas"]),
        (1, 0, 1, 0, 1, 1, 1): ("Pargo al horno con salsa de limón y hierbas", ["Porotos", "Espárragos a la parrilla"]),
        (1, 0, 1, 1, 0, 0, 0): ("Pollo relleno de espinacas y queso feta", ["Arroz integral", "Lentejas"]),
        (1, 0, 1, 1, 0, 0, 1): ("Filete de res con puré de papas y salsa de champiñones", ["Champiñones salteados", "Sopa"]),
        (1, 0, 1, 1, 0, 1, 0): ("Pasta carbonara con panceta", ["Porotos", "Arroz blanco"]),
        (1, 0, 1, 1, 0, 1, 1): ("Bistec con puré de papas", ["Batatas fritas cubiertas con crema agria", "Risotto de hongos"]),
        (1, 0, 1, 1, 1, 0, 0): ("Chuletas de cerdo con salsa de manzana", ["Puré de manzana", "Verduras al vapor"]),
        (1, 0, 1, 1, 1, 0, 1): ("Canelones de carne con salsa bechamel", ["Ensalada mixta", "Sopa"]),
        (1, 0, 1, 1, 1, 1, 0): ("Salmón a la parrilla con salsa de limón y eneldo", ["Espárragos a la parrilla", "Risotto de hongos"]),
        (1, 0, 1, 1, 1, 1, 1): ("Salmón a la mantequilla con espárragos", ["Ensalada mixta", "Puré de papas"]),
        (1, 1, 0, 0, 0, 0, 0): ("Burrito gigante cargado de carne, queso, arroz y frijoles", ["Papas fritas con cheddar y panceta", "Ensalada mixta"]),
        (1, 1, 0, 0, 0, 0, 1): ("Plato de nachos con carne, queso derretido, guacamole y crema agria", ["Espárragos a la parrilla", "Champiñones salteados"]),
        (1, 1, 0, 0, 0, 1, 0): ("Fish and chips con aderezo de tartaar", ["Ensalada mixta", "Papas fritas con cheddar y panceta"]),
        (1, 1, 0, 0, 0, 1, 1): ("Sándwich de pollo frito con tocino y mayonesa", ["Porotos", "Arroz integral"]),
        (1, 1, 0, 0, 1, 0, 0): ("Plato de alitas de pollo picantes con salsa de queso azul", ["Ensalada mixta", "Papas fritas con cheddar y panceta"]),
        (1, 1, 0, 0, 1, 0, 1): ("Lasagna de carne con varias capas de queso", ["Espárragos a la parrilla", "Macarrones con queso"]),
        (1, 1, 0, 0, 1, 1, 0): ("Camarones fritos con salsa agridulce y arroz frito", ["Ensalada mixta", "Puré de papas"]),
        (1, 1, 0, 0, 1, 1, 1): ("Bistec empanizado con salsa de champiñones y papas gratinadas", ["Verduras al vapor", "Risotto de hongos"]),
        (1, 1, 0, 1, 0, 0, 0): ("Tacos de cerdo desmenuzado con queso fundido y guacamole", ["Arroz blanco", "Espárragos a la parrilla"]),
        (1, 1, 0, 1, 0, 0, 1): ("Pastel de carne con puré de papas y salsa gravy", ["Ensalada mixta", "Puré de papas"]),
        (1, 1, 0, 1, 0, 1, 0): ("Pollo frito con queso", ["Arroz blanco", "Papas fritas con cheddar y panceta"]),
        (1, 1, 0, 1, 0, 1, 1): ("Pollo alfredo con pasta cargada de queso parmesano", ["Verduras al vapor", "Macarrones con queso"]),
        (1, 1, 0, 1, 1, 0, 0): ("Ñoquis a la bolognesa",[]),
        (1, 1, 0, 1, 1, 0, 1): ("Chuletas de cerdo empanizadas", ["Ensalada mixta", "Puré de papas"]),
        (1, 1, 0, 1, 1, 1, 0): ("Risotto de langosta con mantequilla", ["Espárragos a la parrilla", "Risotto de hongos"]),
        (1, 1, 0, 1, 1, 1, 1): ("Ensalada de pollo frito con aderezo ranch", ["Ensalada mixta", "Papas fritas con cheddar y panceta"]),
        (1, 1, 1, 0, 0, 0, 0): ("Pechuga de pato confitada con salsa de cerezas y puré de patatas", ["Ensalada mixta", "Puré de papas"]),
        (1, 1, 1, 0, 0, 0, 1): ("Cordero asado con salsa de menta y patatas asadas", ["Verduras al vapor", "Puré de papas"]),
        (1, 1, 1, 0, 0, 1, 0): ("Ternera a la parrilla con salsa de mantequilla de ajo", ["Ensalada mixta", "Papas fritas con cheddar y panceta"]),
        (1, 1, 1, 0, 0, 1, 1): ("Chuletas de cerdo glaseadas con miel y melaza, servidas con puré de batatas", ["Batatas asadas", "Lentejas"]),
        (1, 1, 1, 0, 1, 0, 0): ("Ensalada César con pollo frito, croutones y aderezo cremoso", ["Ensalada mixta", "Croutones"]),
        (1, 1, 1, 0, 1, 0, 1): ("Pechuga de pollo rellena de jamón y queso con salsa de champiñones", ["Champiñones salteados", "Arroz blanco"]),
        (1, 1, 1, 0, 1, 1, 0): ("Camarones al ajillo con arroz blanco y pan de ajo", ["Arroz blanco", "Pan de ajo"]),
        (1, 1, 1, 0, 1, 1, 1): ("Pasta carbonara con panceta y queso parmesano", ["Macarrones con queso", "Champiñones salteados"]),
        (1, 1, 1, 1, 0, 0, 0): ("Costillas de cerdo a la barbacoa con puré de papas y salsa de mantequilla", ["Puré de papas", "Salsa de mantequilla"]),
        (1, 1, 1, 1, 0, 0, 1): ("Filete mignon con salsa de vino tinto y espárragos envueltos en tocino", ["Espárragos a la parrilla", "Arroz integral"]),
        (1, 1, 1, 1, 0, 1, 0): ("Pollo a la parrilla con salsa de queso cheddar y papas al horno cargadas", ["Papas al horno cargadas", "Ensalada mixta"]),
        (1, 1, 1, 1, 0, 1, 1): ("Tacos de carne asada con guacamole y queso derretido", ["Guacamole", "Queso derretido"]),
        (1, 1, 1, 1, 1, 0, 0): ("Pizza de carne con extra de queso y pepperoni", []),
        (1, 1, 1, 1, 1, 0, 1): ("Bone Steak con cargado de queso y tocino", []),
        (1, 1, 1, 1, 1, 1, 0): ("Pastel de cangrejo con salsa de mantequilla", []),
        (1, 1, 1, 1, 1, 1, 1): ("Hamburguesa doble con queso, tocino y salsa especial", ["Papas fritas con cheddar y panceta"])
    }

bebidas = {
    (0, 0, 0, 0): "Agua",
    (0, 0, 0, 1): "Agua Saborizada",
    (0, 0, 1, 0): "sprit,light",
    (0, 0, 1, 1): "coc,light",
    (0, 1, 0, 0): "Té helado",
    (0, 1, 0, 1): "jugo,naturales",
    (0, 1, 1, 0): "Refresco de lim,limón",
    (0, 1, 1, 1): "Limonada",
    (1, 0, 0, 0): "Licuados",
    (1, 0, 0, 1): "Fanta",
    (1, 0, 1, 0): "Sprite",
    (1, 0, 1, 1): "Coca comun",
    (1, 1, 0, 0): "Cerveza",
    (1, 1, 0, 1): "Vino tinto",
    (1, 1, 1, 0): "Gin tonic",
    (1, 1, 1, 1): "Cóctel de margarita"
}
acompañamientos = {
    (0, 0, 0, 0): "Ensalada mixta",
    (0, 0, 0, 1): "Arroz integral",
    (0, 0, 1, 0): "Verduras al vapor",
    (0, 0, 1, 1): "Puré de papas",
    (0, 1, 0, 0): "Puré de manzana",
    (0, 1, 0, 1): "Arroz blanco",
    (0, 1, 1, 0): "Lentejas",
    (0, 1, 1, 1): "Batatas asadas",
    (1, 0, 0, 0): "Porotos",
    (1, 0, 0, 1): "Espárragos a la parrilla",
    (1, 0, 1, 0): "Sopa",
    (1, 0, 1, 1): "Champiñones salteados",
    (1, 1, 0, 0): "Batatas fritas cubiertas con crema agria",
    (1, 1, 0, 1): "Macarrones con queso",
    (1, 1, 1, 0): "Risotto de hongos",
    (1, 1, 1, 1): "Papas fritas con cheddar y panceta"
}

### (muy bajos en calorias) agua    Peps,light
#  bajos en calorias)  Aquarius té helado 
# (altos en calorias)    licuados
# (exceso de calorias) daikiri vino whisky gin tonic
